---
- name: Install and Configure MySQL 8.0
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:

    - name: Install MySQL Server
      dnf:
        name: mysql-server
        state: present

    - name: Start and Enable MySQL Service
      systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: Install MySQL Python Libraries
      ansible.builtin.pip:
        name:
          - cryptography
          - PyMySQL
        executable: pip3

    - name: Ensure MySQL root password is set
      community.mysql.mysql_user:
        name: root
        password: ExpenseApp@1
        login_unix_socket: /var/lib/mysql/mysql.sock
        host_all: yes
        priv: "*.*:ALL,GRANT"
        state: present



    - name: Remove Anonymous Users
      community.mysql.mysql_user:
        name: ""
        host_all: yes
        state: absent
        login_user: root
        login_password: ExpenseApp@1


    - name: Remove Test Database
      community.mysql.mysql_db:
        name: test
        state: absent
